[package]
name = "app"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lcms2 = "6.1.0"

[patch.crates-io]
lcms2-sys = { git = 'https://github.com/Hajime-san/rust-lcms2-sys', branch = 'patched' }
